name: Sbt Publish

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

permissions:
  contents: write
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test
    - name: Package
      env:
        PG4SCALA_VERSION: ${{ env.VERSION }}
      run: sbt package
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: core/target/scala-2.13/pg4scala-core_2.13-${{ env.VERSION }}.jar