name: Sbt Publish

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

permissions:
  packages: write
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      env:
        PG4SCALA_VERSION: ${{ steps.get_version.outputs.VERSION }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sbt test
    - name: Publish
      env:
        PG4SCALA_VERSION: ${{ steps.get_version.outputs.VERSION }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sbt publish
